#This python3 program was created for creating automated income in PSP Socom
#Simply Run this program at Mission start Page
import time
from pykeyboard import PyKeyboard
k = PyKeyboard()
k.tap_key('x')
k.press_key('x')
time.sleep(0.7)
k.release_key('x')
for x in range(1,4):
  time.sleep(0.2)
  for i in range(1,4):
      k.tap_key('Left')
      k.press_key('Left')
      time.sleep(0.3)
      k.release_key('Left')
      time.sleep(0.3),i
#  k.tap_key('Left')
#  k.press_key('Left')
#  time.sleep(0.7)
#  k.release_key('Left')
  time.sleep(0.1)
  k.tap_key('x')
  k.press_key('x')
  time.sleep(0.7)
  k.release_key('x')
  time.sleep(0.2)
  k.tap_key('Right')
  k.press_key('Right')
  time.sleep(0.4)
  k.release_key('Right')
  time.sleep(0.3)
  k.tap_key('Down')
  k.press_key('Down')
  time.sleep(0.5)
  k.release_key('Down')
  k.tap_key('x')
  k.press_key('x')
  time.sleep(0.2)
  k.release_key('x')
  k.tap_key(' ')
  k.press_key(' ')
  time.sleep(0.7)
  k.release_key(' ')
  k.tap_key('Tab')
  k.press_key('Tab')
  time.sleep(0.8)
  k.release_key('Tab')
  time.sleep(0.2)
  k.tap_key('x')
  k.press_key('x')
  time.sleep(0.2)
  k.release_key('x')
  k.tap_key('Tab')
  k.press_key('Tab')
  time.sleep(2)
  k.release_key('Tab')
  time.sleep(0.2)
  k.tap_key(' ')
  k.press_key(' ')
  time.sleep(0.7)
  k.release_key(' ')
  time.sleep(0.2)
  k.tap_key('Up')
  k.press_key('Up')
  time.sleep(0.2)
  k.release_key('Up')
  k.tap_key('x')
  k.press_key('x')
  time.sleep(0.7)
  k.release_key('x')
  k.tap_key('Left')
  k.press_key('Left')
  time.sleep(0.2)
  k.release_key('Left')
  k.tap_key('x')
  k.press_key('x')
  time.sleep(0.7)
  k.release_key('x')
  k.tap_key('Tab')
  k.press_key('Tab')
  time.sleep(1)
  k.release_key('Tab')
  time.sleep(0.1)
  k.tap_key('x')
  k.press_key('x')
  time.sleep(0.5)
  k.release_key('x')
  time.sleep(0.7),x
